language: php

dist: trusty

branches:
  only:
    - master

php:
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 7.1

before_install:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update -q
  - composer self-update
  - mysql -e 'CREATE DATABASE pr0verter;'

services:
  - mysql

install:
  - sudo apt-get install -y ffmpeg
  - composer update
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate
  -

script:
  - vendor/bin/phpunit --verbose